version: '3'

services:
  nginx:
    ports:
      - "80:80"

  mysql:
    ports:
      - "3306:3306"

  php:
    volumes:
      - ./etc/php/php.ini:/etc/php7/conf.d/90-php.ini
    ports:
      - "2323:22"
