version: '3'

services:

  nginx:
    image: nginx:1.15-alpine
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/app
    depends_on:
      - php

  php:
    build:
      context: etc/php
      args:
        APP_DIR: $DOCKER_PHP_APP_DIR
        COMPOSER_VERSION: 1.9.2
    environment:
        PHP_IDE_CONFIG: ${PHP_IDE_CONFIG}
        DATABASE_HOST: ${MYSQL_HOST}
        DATABASE_PORT: ${MYSQL_PORT}
        DATABASE_NAME: ${MYSQL_DATABASE}
        DATABASE_USER: ${MYSQL_USER}
        DATABASE_PASS: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - .:$DOCKER_PHP_APP_DIR
    depends_on: [ mysql ]

  frontend:
    image: node:12
    user: node
    working_dir: /home/node/app
    environment:
      - NODE_ENV=${FRONTEND_ENV-dev}
    volumes:
      - ./:/home/node/app
    expose: [8081]
    command: npm run container-start-${FRONTEND_ENV:-dev}

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
