import_games:
    methods: GET
    path: /api/execute/import_games
    controller: PlayOrPay\UI\Http\Rest\Controller\PassthroughCommand\PassthroughCommandController
    defaults:
        command: PlayOrPay\Application\Command\Steam\Game\ImportSteamGamesCommand

import_game:
    methods: POST
    path: /api/execute/import_game
    controller: PlayOrPay\UI\Http\Rest\Controller\PassthroughCommand\PassthroughCommandController
    defaults:
        command: PlayOrPay\Application\Command\Steam\Game\ImportSteamGameCommand

search_games:
    methods: GET
    path: /api/games
    controller: PlayOrPay\UI\Http\Rest\Controller\PassthroughQuery\PassthroughQueryController
    defaults:
        query: PlayOrPay\Application\Query\Game\Game\Search\SearchGamesQuery
